sudo: required
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false

# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
script: 
  - "echo ###################### WI-CLI ##########################"
  - "pushd tooling"
  - "npm run sdk"
  - "npm install"
  - "gulp"
  - "pushd dist"
  - "tar cvfz wi-cli.tar.gz *"
  - "popd"
  - "popd"
  - "echo ###################### COMPLETED ##########################"


after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
