sudo: false

language: go

go:
  - 1.15.12

os:
  - linux

branches:
  only:
  - master

install:
  - go get github.com/gohugoio/hugo@v0.83.1

script:
  - cd docs && hugo
  - cd public && ls -alh

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: docs/public
  github_token: $GITHUB_TOKEN
  email: $EMAIL
  name: vijaynalawade
  on:
    branch: master

