apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-graphql
spec:
  selector:
    matchLabels:
      app: bookstore-graphql
  template:
    metadata:
      labels:
        app: bookstore-graphql
    spec:
      containers:
      - name: bookstore-graphql
        image: flogo/bookstore-graphql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7879
        envFrom:
        - configMapRef:
            name: bookstore-graphql

---

apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: LoadBalancer
  ports:
  - name: graphql
    port: 17879
    targetPort: 7879
  selector:
    app: bookstore-graphql
