title: 'TCI Web Integrator'
subtitle: 'SDK API Documentation '
permalink: /:title
baseurl: '/tci-webintegrator'
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
include: 
   - designtime/wi-studio/v1.0.0/modules/*.html
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed