# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TCI Web Integrator
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   TIBCO Cloud Integration is a way to seamlessly connect cloud-based 
#   services and on-premises applications, and easily model, create, test, 
#   and deploy custom APIs.

baseurl: "/tci-webintegrator" # the subpath of your site, e.g. /blog
url: "https://github.com/TIBCOSoftware" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
# find ./designtime -name _*.html | sed "s#.*/##g"| sed "s#^#  - #" 
include: 
  - _app_contrib_wi_contrib_.abstractcontribactionprovider.html
  - _app_contrib_wi_contrib_.abstractcontribfieldprovider.html
  - _app_contrib_wi_contrib_.abstractcontribvalidationprovider.html
  - _app_contrib_wi_contrib_.wicontributionutils.html
  - _app_contrib_wi_contrib_.wiproxycorsutils.html
  - _app_contrib_wi_contrib_.wiservicecontribution.html
  - _app_contrib_wi_contrib_.wiservicehandlercontribution.html
  - _app_contrib_wi_contrib_.wiserviceprovidercontribution.html
  - _common_models_contrib_.actionresult.html
  - _common_models_contrib_.authenticationresult.html
  - _common_models_contrib_.contributiontypeconverter.html
  - _common_models_contrib_.oauthdata.html
  - _common_models_validation_.validationerror.html
  - _common_models_validation_.validationresult.html
  - _common_models_validation_.enumvalidationstate.html
  - _app_contrib_wi_contrib_.icontribactionprovidermap.html
  - _app_contrib_wi_contrib_.icontribfieldprovidermap.html
  - _app_contrib_wi_contrib_.icontribvalidationprovidermap.html
  - _app_contrib_wi_contrib_.wicontribmetadata.html
  - _common_models_contrib_.iactiondefinition.html
  - _common_models_contrib_.iactionresult.html
  - _common_models_contrib_.iactivitycontribution.html
  - _common_models_contrib_.iauthenticationresult.html
  - _common_models_contrib_.ibaseservicecontribution.html
  - _common_models_contrib_.ibasicauthdata.html
  - _common_models_contrib_.iconnectionallowedvalue.html
  - _common_models_contrib_.iconnectorcontribution.html
  - _common_models_contrib_.icontribactionprovider.html
  - _common_models_contrib_.icontribfieldprovider.html
  - _common_models_contrib_.icontributioncontext.html
  - _common_models_contrib_.icontributiondisplay.html
  - _common_models_contrib_.icontributionhandler.html
  - _common_models_contrib_.icontribvalidationprovider.html
  - _common_models_contrib_.ifielddefinition.html
  - _common_models_contrib_.ifielddisplay.html
  - _common_models_contrib_.ifunctionargs.html
  - _common_models_contrib_.ifunctioncontribution.html
  - _common_models_contrib_.ihandlerdefinition.html
  - _common_models_contrib_.ioauthdata.html
  - _common_models_contrib_.itriggercontribution.html
  - _common_models_contrib_.iwiservicecontribution.html
  - _common_models_contrib_.iwiservicehandlercontribution.html
  - _common_models_contrib_.iwiserviceprovidercontribution.html
  - _common_models_validation_.ivalidationerror.html
  - _common_models_validation_.ivalidationresult.html
  - _common_types_.jsonschematypeinfo.html
  - _app_contrib_wi_contrib_.html
  - _common_models_contrib_.html
  - _common_models_validation_.html
  - _common_types_.html